name: Preferred Language Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  android-armv7:
    uses: ./.github/workflows/main.yaml
    permissions:
      packages: write
      pull-requests: write
    with:
      platform: android-armv7
      nightly: false
    secrets:
      datadog_api_key: ${{ secrets.DD_API_KEY }}
